### ISSUE TITLE
Issue with 'future_stack'

### ISSUE THREAD

**Issue by NiloofarM71** [drexelwireless/dragonradio#5]
I am getting the following error running sc2-diagnostics /common_logs/RESERVATION-147532

Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1353, in apply
    result = self._python_apply_general(f, self._selected_obj)
  File "/venv/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1402, in _python_apply_general
    values, mutated = self.grouper.apply(f, data, self.axis)
  File "/venv/lib/python3.10/site-packages/pandas/core/groupby/ops.py", line 767, in apply
    res = f(group)
  File "/venv/lib/python3.10/site-packages/dragonradio/tools/colosseum/scoring.py", line 414, in fillMissingMPs
    return df.unstack(â'team', 'stage', 'flow_uid'ê).reindex(range(stage_start, stage_end+1)).fillna(0).stack(â'team', 'stage', 'flow_uid'ê, future_stack=True)
TypeError: DataFrame.stack() got an unexpected keyword argument 'future_stack'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/bin/sc2-diagnostics", line 8, in <module>
    sys.exit(sc2_diagnostics())
  File "/venv/lib/python3.10/site-packages/dragonradio/tools/colosseum/command_line/sc2_diagnostics.py", line 252, in sc2_diagnostics
    cmd.run('Provide diagnostics based on SC2 score')
  File "/venv/lib/python3.10/site-packages/dragonradio/tools/colosseum/command_line/command.py", line 76, in run
    return self.handle(parser, args)
  File "/venv/lib/python3.10/site-packages/dragonradio/tools/colosseum/command_line/sc2_diagnostics.py", line 193, in handle
    for offender, point_loss in problem_srns(scorer):
  File "/venv/lib/python3.10/site-packages/dragonradio/tools/colosseum/command_line/sc2_diagnostics.py", line 221, in problem_srns
    for _, row in scorer.flows.iterrows():
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/venv/lib/python3.10/site-packages/dragonradio/tools/colosseum/scoring.py", line 661, in flows
    score_df = self.per_mp_score
  File "/venv/lib/python3.10/site-packages/dragonradio/tools/cache.py", line 82, in __get__
    df = self.func(instance)
  File "/venv/lib/python3.10/site-packages/dragonradio/tools/colosseum/scoring.py", line 416, in per_mp_score
    df = df.groupby(â'stage'ê, as_index=False).apply(fillMissingMPs).droplevel(0)
  File "/venv/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1363, in apply
    return self._python_apply_general(f, self._obj_with_exclusions)
  File "/venv/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1402, in _python_apply_general
    values, mutated = self.grouper.apply(f, data, self.axis)
  File "/venv/lib/python3.10/site-packages/pandas/core/groupby/ops.py", line 767, in apply
    res = f(group)
  File "/venv/lib/python3.10/site-packages/dragonradio/tools/colosseum/scoring.py", line 414, in fillMissingMPs
    return df.unstack(â'team', 'stage', 'flow_uid'ê).reindex(range(stage_start, stage_end+1)).fillna(0).stack(â'team', 'stage', 'flow_uid'ê, future_stack=True)
TypeError: DataFrame.stack() got an unexpected keyword argument 'future_stack'

**Comment by mainland** [comment]
What version of the tools are you using (a git hash would be great), and how did you build them?
